services: mongodb
language: ruby
script: "bundle exec rake spec"
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
env:
  - CODECLIMATE_REPO_TOKEN=09d5b03158ed324e25726a0cca45311ab052b8b7229c6fbfbf0155fcf822e411
gemfile:
  - gemfiles/mongoid_3.gemfile
  - gemfiles/mongoid_4.gemfile
notifications:
  email: false
addons:
  code_climate:
    repo_token: 09d5b03158ed324e25726a0cca45311ab052b8b7229c6fbfbf0155fcf822e411